language: node_js
node_js:
- 8.4.0
services:
- postgresql
before_script:
- npm run lint
- mv config/config.example.js config/config.js
- npm run sequelize -- --env test db:create
- npm run sequelize -- --env test db:migrate
after_success:
- npm run report:coverage -- --reporter=text-lcov | coveralls
deploy:
  app:
    master: express-starter
  provider: heroku
  api_key:
    secure: aqamqm34fGv5BJ5NbctSSAoCSnlMel5gYuTJ8k3+0Dfti2BNQ79qPb9q+CFbAKJZsTXzVKlWGd2oH1AvKieUspHEPVPVe5qLAwtjJKz39Ej/q/choJRUb5cJbIB32X6iyLuLAZGzZ5Rr2tzUZ9/RpXmfMBea4hnVJuVOBzI764GQ8Mi/uKm4vAkSnI7aGOnT1jhLvw8GB3jVc+pL3aSrNmAq1McG1Hpn0wbn4SWZgKfDtmIEpsCBryNTfb7AF4Sko74pbn8EutaaJfpsAnGzZxlj+DwCn2VTrcFpqM9F7K1b5yUYoRfrzTYVmMHoM/kqdr9HR2OX1QxBU9tPcMVbZhOX5+C7GehgTaM2s6Tvc6sXFPgFKp/cTnDq0Ze5/+VdkJoPBX/cAGAm054wyUwcvoOiCxjouBm6HKR8jWQ8g5ZfhzXd8NY2FW8fN+LydlLrEJqKskJw+sTz6M6h6HDzckVlN9gNe4Q4G2xE9zdTCeMiSxepJRw0r9zqqzAU/R5kvMlQ70lYNcS5yWeTS6587UaBoxsofa7Ako8gYbav7hV2jJw7sbmWPPJi9xXnDcj6t2S/0W2sqAv3+h9PBnpeJsULm/DRwDJrhiGLhr4oXtFPnvwvMySUgxJRvamfEdOSL794797ZhEygq33IaBVbtOyAqr+LyVAhC1w3HxTXouY=
