language: node_js
node_js:
- 8.4.0
services:
- postgresql
before_script:
- npm run lint
- mv config/config.example.js config/config.js
- npm run sequelize -- --env test db:create
- npm run sequelize -- --env test db:migrate
after_success:
- npm run report:coverage -- --reporter=text-lcov | coveralls
deploy:
  app:
    master: express-starter
  provider: heroku
  api_key:
    secure: FLocj1gujW9HRTvbrdcGJTnT7suzffGGvuqPnz2xpksNwP5wl5XvlmbFYfTgD4YljtbvwW9YWp6v/mfs3SkZ2y/dHBKjbl5t+MMweMh4lt6buoZGx6eoUhhvrlsOTjVmxiv3ToGpb7me4zut+vA2KPUGQYz89rQfwxSbFzG0JtrGvFsLNi6W5suK7uI88+xMgivX9peJ93wytqEo57fwJznrWFvadNsF4BiHTcGBuNuklyOYDcSYcLgT/wAt4HgvCXbupdjFcZrnQf0+n1cBiBqlozu1k955iHst5+dgGJMyC16dkpFyoBqLa+VV3NrcIEqYxnIr1d+IlRPRX/PMgbZdCe9LPvnbu9/hEUyZWF5NoAMmha2lOrUCTIW57OrP3cIBDt3U/mU9ADS33Gz5Jnz7WGXNlfG7GWNgcIGyKO2gwPVpqZKCUxJyjH5Rj8Iwd1SbLqS3X8VCuu5y8FJBKQ+elb3roIcFvPHx+UuIWi4QjAAauJ0CnNrMUOgfFvW6fieF2gSBcuSvqPVfRWRFj6cmy80fMhmg0L4ZRhMUn3y31npwN5piSDZ5P54K7SL1am5X0GPgmPhpfbDkcvNmc59cEDKFduNf29lW+vmHlIVADXZeo8PiUwTZlZN7fbwwOTl48jMUt67ViZEHikqTl6yMuoyhA/AfZH8y0yG86R8=
